#Adicionar GitHub Action para compilação
name: Build EirusAlpha

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 PyQtWebEngine requests pyinstaller
    
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name="EirusAlpha" browser.py
    
    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        name: EirusAlpha-Windows
        path: dist/EirusAlpha.exe
        retention-days: 30

  build-linux:
    runs-on: ubuntu-20.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pyqt5 python3-pyqt5.qtwebengine python3-pyqt5-dev-tools qtbase5-dev qt5-qmake
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 PyQtWebEngine requests pyinstaller
    
    - name: Build executable
      run: |
        pyinstaller --onefile --name="EirusAlpha" browser.py
    
    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        name: EirusAlpha-Linux
        path: dist/EirusAlpha
        retention-days: 30
